Repository rfmineguy/lldb-frontend, pull requests merged in 2025-07, with the labels that each got.

#50 [refactor] use Zeuns repo for ImGuiIniParser
  CMakeLists.txt
  src/ImGuiIniParser.cpp
  src/ImGuiIniParser.hpp
  src/Init.cpp
  src/liblldbfrontend.cpp
Labels: refactor

#56 Fixed problem where running process didnt get killed on window close
  src/LLDBDebugger.cpp
Labels: bug-fix

#59 Imgui lldb thread view and locals view
  autoexec_example
  src/ImGuiLayer.cpp
  src/ImGuiLayer.hpp
  test/nested/nested.cpp
  test/nested/nested.hpp
  test/test.cpp
Labels: enhancement

#66 Supply arguments to process
  .github/workflows/windows.yml
  cmake/CompilerFlags.cmake
  cmake/Install.cmake
  src/Args.cpp
  src/Args.hpp
  src/ImGuiLayer.cpp
  src/ImGuiLayer.hpp
  src/LLDBDebugger.cpp
  src/LLDBDebugger.hpp
  src/Util.cpp
  src/Util.hpp
  src/main.cpp
  test/test.cpp
Labels: CLI
